june-2020/demo-website/console_main/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls import url
from qr_code import urls as qr_code_urls
from . import views

app_name = "console_main"

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^at/', include('admin_tools.urls')),
    url(r'^$', views.landing, name="landing"),
    path('check_ela_auth', views.check_ela_auth, name="check_ela_auth"),
    path('did_callback_elastos', views.did_callback_elastos, name="did_callback_elastos"),
    url(r'^qr_code/', include(qr_code_urls, namespace='qr_code')),
    url(r'^login/', include('login.urls'), name='login'),
]

june-2020/demo-website/login/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "login"

urlpatterns = [
    path('register', views.register, name="register"),
    path('edit_profile', views.edit_profile, name="edit_profile"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name="activate"),
    path('sign_out', views.sign_out, name="sign_out"),
]

june-2020/demo-website/templates/base.html
{% load sass_tags %}{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Use jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>


    <!-- Required meta tags -->
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T"  crossorigin="anonymous"/>

    <!-- Sass files -->
    <link href="{% sass_src 'scss/sidebar.scss' %}" rel="stylesheet" type="text/css"/>
    <link href="{% sass_src 'scss/modal.scss' %}" rel="stylesheet" type="text/css"/>

    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}"/>

    <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Overpass&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles-new.css' %}"/>

    <!-- Title -->
    {% block title %}{% endblock %}

    <!-- Custom Javascript files -->
    {% block scripts %}{% endblock %}

    <!-- Header -->
    <header>
        <nav class="navbar navbar-expand-lg flex-column flex-md-row">
            <a href="{% url 'landing' %}">
                <img src="{% static 'images/common/icon.svg' %}" class="logo-converted"
                     alt="Demo Website Logo"/>
            </a>
            {% if request.session.logged_in == True %}
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-oggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" style="padding-left: 1rem;">
                </div>

                <div class="dropdown">
                    <a class="nav-link dropdown-toggle text-white" href="#" role="button" id="accountDropdown"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Account</a>
                    <div class="dropdown-menu dropdown-menu-right others-submenu" aria-labelledby="accountDropdown">
                        <a class="dropdown-item" href="{% url 'login:edit_profile' %}">Edit Profile</a>
                        <a class="dropdown-item" href="{% url 'login:sign_out' %}">Log Out</a>
                    </div>
                </div>
            {% endif %}
        </nav>
    </header>
</head>
<body>

<!-- Body Content -->
<div class="django_messages">
    {% if messages %}
        {% for message in messages %}
            <p class="alert alert-info">{{ message }}</p>
        {% endfor %}
    {% endif %}
</div>

<div class=container-fluid">
    {% block content %}
    {% endblock %}
</div>

<!-- Footer -->
<footer class="footer">
    <div class="text-center">
        <p>
            <a class="link" href="http://www.tuum.tech" target="_blank">Tuum.tech</a>
        </p>
        <p>
            <span class="copyright">Copyright © 2020 Tuum Technologies. All Rights Reserved.</span>
        </p>
    </div>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script
        src="https://code.jquery.com/jquery-3.4.1.js"
        integrity="sha256-WpOohJOqMqqyKL9FccASB9O0KwACQJpFTUBLTYOVvVU="
        crossorigin="anonymous"
></script>
<script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
        crossorigin="anonymous"
></script>
<script
        src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
        crossorigin="anonymous"
></script>
<!-- Google Prettify for code syntax highlighting -->
<script src="https://cdn.jsdelivr.net/gh/google/code-prettify@master/loader/run_prettify.js??lang=python&lang=go;skin=desert"></script>
</body>
</html>

june-2020/demo-website/templates/landing.html
{% extends 'base.html' %} 
{% load static %}
{% load django_simple_cookie_consent_tags %}
{% load qr_code %}
{% block title %}
  <title>Landing - Demo Website</title>
    {% display_cookie_consent %}
{% endblock title %}

{% block scripts %}
    <link href="{% static 'css/landing.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static '/javascript/elaauth.js' %}"></script>
{% endblock %}

{% block content %}
<main class="bd-masthead" role="main" style="background-color: #181b22;">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-6 mx-auto col-md-6 order-md-2">
            <img src="{% static '/images/common/main-pattern.svg' %}"/>
        </div>
        <div class="col-md-6 order-md-1 text-center text-white text-md-left pr-md-5">
          <h1>How to Add Decentralized ID Login to any App</h1>
          <p class="jumbotron-text">In
              centralized identity systems, individuals do not have control over their personal information,
              and in a worst case scenario, services have been known to maliciously leak or share personal
              information without the user's knowledge.

              DID is completely under the control of the DID subject, without reliance on any centralized
              registration body, commercial identity provider, or organization issuing certificates.
              The encryption materials integrated with the verification
              methods provides a set of identify verification mechanisms (such as a public key, anonymous
              biological identification agreement, etc.), with other optional parts that can be used according
              to the needs of the application and of the user.
          </p><br><br><br><br>
          <div class="row mx-n2" style="margin-top: 45px;">
            <div class="col-md px-2">
                {% if request.session.logged_in != True %}
                    <button class="login-button" data-toggle="modal" data-target="#myModal">
                            Login with Elastos DID
                    </button>
                {% endif %}
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-body">
                    <div class="tab-content">
                        <div class="tab-pane active" id="elastOS">
                            <div class="row align-items-center justify-content-center">
                                <div class="col-md-12 text-center">
                                    <h4 class="login-header">
                                        Scan the code with elastOS
                                    </h4>
                                </div>
                                <div class="col-md-12 text-center">
                                    <p class="scan-qr-text">
                                        You can download the app on both Android and iOS devices. For more info, download it from
                                        App Store or go to
                                        <a href="https://www.elastos.org/" target="blank" style="color: #f48424;">Official ElastOS Website</a>
                                    </p>
                                </div>
                                <div class="col-md-12 text-center">
                                    <img src="{% qr_url_from_text elastos_url error_correction='Q' size=3 version=10 image_format='png' %}" style="margin-top: 1rem;"/>
                                </div>
                                <div class="col-md-12 text-center">
                                    <p class="scan-qr-wait">
                                        Waiting for phone authentication...
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</main>

  <!-- Our Mission Row -->
  <main class="bd-masthead" role="main" style="background-color: #242a37;">
      <div class="container">

          <!-- Description -->
          <div class="row justify-content-center m-45px-b md-m-20px-b sm-m-15px-b">
              <div class="col-12 col-md-10 col-lg-7">
                <div class="section-title text-center">
                  <h2 style="font-family: 'Overpass', sans-serif;color: #ffffff;font-size: 44px;">Agenda</h2>
                  <p class="main-content">Learn just how easy it is to add a decentralized ID login to any
                      of your apps using Elastos technology.
                  </p>
                </div>
              </div>
          </div>

          <!-- Our Mission -->
          <div class="row" style="margin-top: 15px;">
              <div class="col-12 col-md-4">
                  <div class="mission-box">
                    <div>
                        <img src="{% static 'images/common/integrated.svg' %}"/>
                        <h4>DID Login from another capsule inside elastOS</h4><br>
                        <p>Check out the source code and demo <a href="https://github.com/tuum-tech/webinars/tree/master/june-2020/demo-elastOS-capsule">here</a>
                        </p>
                    </div>
                  </div>
              </div>
              <div class="col-12 col-md-4">
                  <div class="mission-box">
                    <div>
                        <img src="{% static 'images/common/interactive.svg' %}"/>
                        <h4>DID Login from an external native app</h4><br>
                        <p>Check out the source code and demo <a href="https://github.com/tuum-tech/webinars/tree/master/june-2020/demo-ionic-app">here</a>
                        </p>
                    </div>
                  </div>
              </div>
              <div class="col-12 col-md-4">
                  <div class="mission-box">
                    <div>
                        <img src="{% static 'images/common/box.svg' %}"/>
                        <h4>DID Login from a website</h4><br>
                        <p>Check out the source code and demo <a href="https://github.com/tuum-tech/webinars/tree/master/june-2020/demo-website">here</a></p>
                    </div>
                  </div>
              </div>
          </div>
      </div>
  </main>

  <main class="bd-masthead" role="main" style="background-color: #00adea;">
    <div class="container">
      <div class="row align-items-center">
        <div class="col-6 mx-auto col-md-6 order-md-2">
            <img src="{% static '/images/common/pattern.svg' %}"/>
        </div>
        <div class="col-md-6 order-md-1 text-center text-white text-md-left pr-md-5">
          <h1 class="jumbotron-header">Start Developing Today</h1>
          <p class="jumbotron-text">
              elastOS provides an easy way for developers to start building any decentralized applications without having
              to learn a lot about how blockchain works underneath. You develop your app exactly how you want, utilize various
              components such as DID, Elastos Carrier, Hive, and Ethereum Smart Contracts and deploy it to multiple platforms
              simultaneously.
          </p><br><br>
          <div class="row mx-n2">
            <div class="col-md px-2">
                <button class="login-button">
                    <a class="login-text" href="https://developer.elastos.org/">
                        Read Documentation
                    </a>
                </button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </main>

{% endblock %}