june-2020/demo-website/console_main/urls.py
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.conf.urls import url
from qr_code import urls as qr_code_urls
from . import views

app_name = "console_main"

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^at/', include('admin_tools.urls')),
    url(r'^$', views.landing, name="landing"),
    path('check_ela_auth', views.check_ela_auth, name="check_ela_auth"),
    path('did_callback_elastos', views.did_callback_elastos, name="did_callback_elastos"),
    url(r'^qr_code/', include(qr_code_urls, namespace='qr_code')),
    url(r'^login/', include('login.urls'), name='login'),
]

june-2020/demo-website/login/urls.py
from django.urls import path
from django.conf.urls import url

from . import views

app_name = "login"

urlpatterns = [
    path('register', views.register, name="register"),
    path('edit_profile', views.edit_profile, name="edit_profile"),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name="activate"),
    path('sign_out', views.sign_out, name="sign_out"),
]

june-2020/demo-website/login/models.py
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.db import models
from django.contrib.postgres.fields import JSONField
from django.utils import timezone

from .managers import DIDUserManager


class DIDUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=255, unique=True)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    name = models.CharField(max_length=255)
    did = models.CharField(max_length=64)
    date_joined = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
    objects = DIDUserManager()

    def __str__(self):
        return self.email

    @staticmethod
    def user_name():
        return 'User Identification Info'


class DIDRequest(models.Model):
    state = models.CharField(max_length=20)
    data = JSONField()
    created_at = models.DateTimeField(default=timezone.now)
    last_updated = models.DateTimeField(auto_now=True)

june-2020/demo-website/login/forms.py
from django import forms
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.forms.widgets import HiddenInput

from .models import DIDUser


class DIDUserCreationForm(UserCreationForm):
    checkbox = forms.BooleanField(help_text=mark_safe("By clicking the checkbox, you acknowledge that you accept our "
                                                      "<a style=\"color: green\" data-toggle=\"modal\" "
                                                      "data-target=\"#privacyPolicy\">Privacy Policy</a> and "
                                                      "<a style=\"color: green\" data-toggle=\"modal\" "
                                                      "data-target=\"#termsAndConditions\">Terms of Conditions</a>."), required=True)

    def __init__(self, *args, **kwargs):
        super(DIDUserCreationForm, self).__init__(*args, **kwargs)
        self.label_suffix = ""
        self.fields['password1'].required = False
        self.fields['password2'].required = False
        self.fields['password1'].widget = HiddenInput()
        self.fields['password2'].widget = HiddenInput()
        self.fields['did'].widget.attrs['readonly'] = True
        self.fields['did'].widget.attrs['style'] = 'color: grey; background-color: lightgrey'
        self.fields['did'].label = "DID"
        self.fields['name'].label = "Nickname"
        self.fields['checkbox'].label = ""

    class Meta:
        model = DIDUser
        fields = ('email', 'name', 'did',)
        widgets = {
            'email': forms.Textarea(attrs={'rows': 1, 'cols': 64}),
            'name': forms.Textarea(attrs={'rows': 1, 'cols': 64}),
            'did': forms.Textarea(attrs={'rows': 1, 'cols': 64}),
        }

    def save(self, commit=True):
        user = super(DIDUserCreationForm, self).save(commit=False)
        user.email = self.cleaned_data['email']
        user.name = self.cleaned_data['name']
        user.did = self.cleaned_data['did']
        if commit:
            user.save()
        return user


class DIDUserChangeForm(UserChangeForm):

    def __init__(self, *args, **kwargs):
        super(DIDUserChangeForm, self).__init__(*args, **kwargs)
        self.label_suffix = ""
        self.fields['password'].required = False
        self.fields['password'].widget = HiddenInput()
        self.fields['did'].widget.attrs['readonly'] = True
        self.fields['did'].widget.attrs['style'] = 'color: grey; background-color: lightgrey'

    class Meta:
        model = DIDUser
        fields = ('email', 'name', 'did',)
        widgets = {
            'email': forms.Textarea(attrs={'rows': 1, 'cols': 64}),
            'name': forms.Textarea(attrs={'rows': 1, 'cols': 64}),
            'did': forms.Textarea(attrs={'rows': 1, 'cols': 64}),
        }

june-2020/demo-website/login/views.py
import gc
from decouple import config

from django.contrib import messages
from django.http import HttpResponse
from django.utils.http import urlsafe_base64_decode
from django.urls import reverse
from django.shortcuts import render, redirect
from django.utils.encoding import force_text

from console_main.views import login_required, send_email

from .models import DIDUser
from .forms import DIDUserCreationForm, DIDUserChangeForm
from .tokens import account_activation_token


def register(request):
    if 'redirect_success' not in request.session.keys():
        return redirect(reverse('landing'))
    if request.method == 'POST':
        form = DIDUserCreationForm(request.POST,
                                   initial={'name': request.session['name'], 'email': request.session['email'],
                                            'did': request.session['did']})
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            to_email = form.cleaned_data.get('email')
            send_email(request, to_email, user)
            request.session['name'] = user.name
            request.session['email'] = user.email
            messages.success(
                request, "Please check your email to complete your registration")
            return redirect(reverse('landing'))
    else:
        form = DIDUserCreationForm(initial={'name': request.session['name'], 'email': request.session['email'],
                                            'did': request.session['did']})
    return render(request, 'login/register.html', {'form': form})


@login_required
def edit_profile(request):
    did_user = DIDUser.objects.get(did=request.session['did'])
    if request.method == 'POST':
        form = DIDUserChangeForm(request.POST, instance=request.user)

        if form.is_valid():
            user = form.save(commit=False)
            # This means the user changed their email address
            if user.email != did_user.email:
                user.is_active = False
                user.save()
                to_email = form.cleaned_data.get('email')
                send_email(request, to_email, user)
                messages.success(
                    request, "Please check your email to finish modifying your profile info")
            else:
                user.save()
            return redirect(reverse('landing'))
    else:
        if did_user.is_active is False:
            send_email(request, did_user.email, did_user)
            messages.success(request,
                             "The email '%s' needs to be verified. Please check your email for confirmation link" % did_user.email)
            return redirect(reverse('landing'))
        form = DIDUserChangeForm(instance=request.user)
    return render(request, 'login/edit_profile.html', {'form': form})


def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = DIDUser.objects.get(did=uid)
    except(TypeError, ValueError, OverflowError, DIDUser.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        messages.success(request, "Email has been confirmed!")
        return redirect(reverse('landing'))
    else:
        return HttpResponse('Activation link is invalid!')


@login_required
def sign_out(request):
    request.session.clear()
    gc.collect()
    did_login = config('DIDLOGIN', default=False, cast=bool)
    if not did_login:
        messages.success(request, "You have disabled DID LOGIN. Unable to log out! Please re-run the server with "
                                  "DIDLOGIN set to True")
    else:
        messages.success(request, "You have been logged out!")
    return redirect(reverse('landing'))

june-2020/demo-website/templates/login/account_activation_email.html
<div class="col-md-12" style="...">
    {% autoescape off %}
        Hi {{ user.name }},<br>
        Please click on the following link to confirm your registration.<br>
        Confirmation Link: http://{{ domain }}{% url 'login:activate' uidb64=uid token=token %}<br>
        Thank you,<br>
        Nucleus Console Team
    {% endautoescape %}
</div>

june-2020/demo-website/templates/login/edit_profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Edit Profile - Elastos Nucleus</title>
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col text-center justify-content-center m-3 p-3" style="background-color: #242a37;">
            <h4 class="login-header">Edit your information below</h4>
            <form class="text-center" method="post">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <p>
                        <span class="form-field-label">{{ field.label_tag }}</span><br>
                        {{ field }}
                        {% if field.help_text %}
                            <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </p>
                {% endfor %}
                <button class="register-button" type="submit" style="margin-bottom: 30px;">Change</button>
            </form>
        </div>
    </div>
{% endblock %}

june-2020/demo-website/templates/login/register.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  <title>Register - Elastos Nucleus</title>
{% endblock title %}

{% block scripts %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/login.css' %}"/>
{% endblock %}

{% block content %}
    <div class="row align-items-center justify-content-center">
        <div class="col-md-12 text-center">
            <h4 class="login-header">Enter your information below</h4>
        </div>
        <div class="col-md-12">
            <form class="text-center" method="post">
                {% csrf_token %}
                {% for field in form.visible_fields %}
                    <p>
                        <span class="form-field-label">{{ field.label_tag }}</span><br>
                        {{ field }}
                        {% if field.help_text %}
                            <small style="color: grey">{{ field.help_text }}</small>
                        {% endif %}
                        {% for error in field.errors %}
                            <p style="color: red">{{ error }}</p>
                        {% endfor %}
                    </p>
                {% endfor %}
                <button class="register-button" type="submit" style="margin-bottom: 30px;">Register</button>
            </form>
        </div>
    </div>
{% endblock %}